services:

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: torrent-qbittorrent
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080

    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads

    ports:
      - "6881:6881"
      - "6881:6881/udp"

  bot:
    build: .
    container_name: telegram-torrent-bot
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8

    env_file:
      - .env

    volumes:
      - ./downloads:/downloads

    depends_on:
      - qbittorrent

    ports:
      - "8080:8080"
